### ISSUE TITLE
Bugged Inventory Screen Zc 0.0.8

### ISSUE THREAD

**Issue by malecoda** [warezit/zitCraft#1]
Tabs are bugged/graphically/not functional.

**Comment by warezit** [comment]
This was a problem with CustomNPCs fighting other mods to create tabs in the inventory screen.

Modified CustomNPCs config to disable creating tabs in inventory screen.

> InventoryGuiEnabled=false

Changes will be in effect on the next release of zitCraft = 0.0.9
