### ISSUE TITLE
Sleeping in bed damages player - zC 0.0.11

### ISSUE THREAD

**Issue by warezit** [warezit/zitCraft#11]
This is an issue with the "Morpheus" mod, I believe.

This is still an issue in zitCraft 0.0.11.
# Place your bed **below Y-Level 64**.

**Comment by warezit** [comment]
This is also true for DecoCraft beds.

**Comment by Rader2146** [comment]
Still a thing?  My bed is well above y64 and works fine.  Cant confirm if it's fixed for all others though.

**Comment by warezit** [comment]
I can no longer reproduce this issue either.

My bed is also well above Y-Level 64, and I do not have any problems. (zC 0.0.15)
