### ISSUE TITLE
Modular Powersuits missing all recipes - zC 0.0.11

### ISSUE THREAD

**Issue by warezit** [warezit/zitCraft#12]
The Modular Powersuits mod is not showing any recipes in NEI.

This is a known problem.

Looking for a fix. Testing QMX release of Modular Powersuits now (for: zC 0.0.12)

**Comment by warezit** [comment]
More details here: https://github.com/QMXTech/MachineMusePowersuits/issues?q=recipe

**Comment by warezit** [comment]
Updated Modular Powersuits mod to QMXTech 0.11.0.6: https://github.com/QMXTech/MachineMusePowersuits/releases/tag/v0.11.0.6-QMX

Recipes still don't show up in NEI, but you are able to craft any item. Recipes are here: http://machinemuse.net/recipes.php

**Comment by MalTeeez** [comment]
Just download the .jar, open with 7-zip and extract the .recipe files to the recipes folder in the machinemuse config folder
