### ISSUE TITLE
Crash loading single player world. - zC 0.0.11 

### ISSUE THREAD

**Issue by Rader2146** [warezit/zitCraft#13]
Existing single player test world and newly generated worlds crash in singleplayer after the 0.0.11 update.

Log:
https://gist.github.com/Rader2146/c9c22741f294fa7c2d50

Numina/Powersuits seems to be the culprit.  Will remove and retest.

**Comment by warezit** [comment]
We should be switching to a more stable build of Powersuits here: https://github.com/QMXTech/MachineMusePowersuits/releases on the the next release of zC (0.0.12) once I can get the recipe thing figured out here: https://github.com/warezit/zitCraft/issues/12

**Comment by warezit** [comment]
Updated Modular Powersuits mod to 0.11.0.6. https://github.com/QMXTech/MachineMusePowersuits/releases/tag/v0.11.0.6-QMX

This should fix this issue.
