### ISSUE TITLE
Using Enhanced Portals causes massive loss of hunger and saturation - zC 0.0.11

### ISSUE THREAD

**Issue by warezit** [warezit/zitCraft#14]
When going thru an Enhanced Portal, the player loses a massive amount of hunger.

Not sure what is causing this. Might be related to Spice of Life, or hunger overhaul.

I will test what is causing this, before the next release of zC (0.0.12).

**Comment by FuzzyJem** [comment]
Ive also gone through a portal, just to instantly get sent back a few times which of course leads to instant 0 hunger

**Comment by warezit** [comment]
Removing HO & SoL in zC 0.0.12.

This "should" fix this issue.

**Comment by warezit** [comment]
Removing Hunger Overhaul and Spice of Life did NOT fix this issue.

Still investigating...

**Comment by warezit** [comment]
This is tested and should be fixed in zC 2.0
