### ISSUE TITLE
Cannot create single player world

### ISSUE THREAD

**Issue by zunzibarr** [warezit/zitCraft#17]
Tried setting up a creative world, all else at default settings, crashes to desktop after a few seconds of trying to load it up. Due to pastebin constraints, only the bottom portion of the log exists here - http://pastebin.com/iHx5vxQU

**Comment by warezit** [comment]
Looks line Numina, the base mod for Modular Powersuits is causing this issue.

I am removing the current version of Modular Powersuits in the next release of zC (0.0.12) because of instability, and also missing recipes.

**Comment by Rader2146** [comment]
QMXTech released an update earlier today.  Fixes recipies and we'll cross our fingers for single player worlds to work again.

https://github.com/QMXTech/MachineMusePowersuits/releases/tag/v0.11.0.6-QMX
