### ISSUE TITLE
FPS/Chunk Update lag zC 0.0.8

### ISSUE THREAD

**Issue by malecoda** [warezit/zitCraft#2]
l5639@3.8/24G/7950/W7/Java 1.8.0_31 x64 or Java 1.7.0_72 x64 6g allocated 1.5-2g used

Game play feels sluggish 16-30 FPS common, chunk updates equal or greater than FPS. 
Both in base and other areas. FPS as low as 3 not uncommon.

Tried:
Using Java 1.8/1.7 x64
fast lighting, clouds, and particles low/disabled
fastcraft, crashes client on world load (SP/MP)

**Comment by warezit** [comment]
I see what you are talking about.

Investigating for the last couple hours, and still looking into it.

I'll get this pinned down today.

**Comment by warezit** [comment]
Pinned issue down to a bad version of NEI.

Rolled NEI back to:

> NotEnoughItems-1.7.10-1.0.4.80-universal.jar

Changes are in effect on zitCraft 0.0.9.

**Comment by warezit** [comment]
Side note:
Confirmed FastCraft (any version for MC 1.7.10) crashing client and server.
