### ISSUE TITLE
payload may not be larger than 32K? - zC 0.0.11

### ISSUE THREAD

**Issue by FuzzyJem** [warezit/zitCraft#20]
![image](https://cloud.githubusercontent.com/assets/10901280/6202589/e8c81a00-b4c1-11e4-9e63-49e3efe8c695.png)

keep getting this message after joining for a few minutes. I get kicked out after about 2 mins of playing after some serious lag.
 not sure what is causing this

**Comment by FuzzyJem** [comment]
in the nether

**Comment by warezit** [comment]
Seems like this is related to the Hats/Hat Stand mod(s).

More details here: https://github.com/micdoodle8/Galacticraft/issues/878

I am not currently aware of how to fix this. I think there is some incompatability between some mods. I will make sure we are running updated versions of these mods on the next update of zC (0.0.12).

**Comment by Rader2146** [comment]
i got this once while in the nether, didnt report because i couldnt reproduce the error

**Comment by warezit** [comment]
TY for letting us know now tho Rader.

Good to know it's not just limited to one user.

**Comment by warezit** [comment]
Updated "Hats" mod from 4.0.0 to 4.0.1 in zC 0.0.12.

Hopefully this fixes this issue.
