### ISSUE TITLE
ProjectE transmutation search? - zC 0.0.14

### ISSUE THREAD

**Issue by FuzzyJem** [warezit/zitCraft#24]
So projectE has a book available that makes it so that everything that has an emc value, can be search in the transmutation table/tablet so you can create it using EMC without having to "teach" the tablet how to make it.The problem I am having is that most items i search for that have a lot of letters ends up only giving me the option to create paint brushes. When you search for something, there are about 10 slots that generate possible items, base off of the similarity in the name. So if i begin typing "iron" in the search bar, iron ingots, iron sword, iron shovel etc pop up, which is fine. However, when i search for something with a longer name like "factory block" the only options that become available are paint brushes and the item i am searching for does not even show up. Is it possible to get rid of EMC values for useless items like the paint brushes so they dont show up on the tablet and the item that is being searched for actually shows?

**Comment by Rader2146** [comment]
After our convo last night I looked into this more.  ProjectE 1.2.0 was released 5 days ago and is supposed to fix this well known bug.

**Comment by warezit** [comment]
FYI - ProjectE has been updated to ProjectE-1.7.10-PE1.2.0 in zC 0.0.15.

http://www.technicpack.net/modpack/zitcraft.581606/changelog
