### ISSUE TITLE
Placing an EnerderThermic Pump too close to a Nether Fortress causes server console spam/lag - zC 0.0.16

### ISSUE THREAD

**Issue by warezit** [warezit/zitCraft#25]
Title says it all.

More details here:
http://forums.technicpack.net/topic/115546-silently-catching-entity-tracking-error-what-to-do/

**Comment by warezit** [comment]
I have since removed all 5 of the EnderThermic Pumps from the Nether, and it still does not fix the console spam. Please see me in-game to get your pump back! (Sorry!)

**Comment by warezit** [comment]
Console spam has been fixed, by this fix: https://github.com/warezit/zitCraft/issues/27

**Comment by warezit** [comment]
Please keep your EnderThermic Pump FAR away from a Nether Fortress.

**Comment by warezit** [comment]
Disabled placing EnderThermicPumps in the Nether in zC 2.0

**Comment by Rader2146** [comment]
Is banning ender-thermic pumps nessisary?  This issue was fixed by #27. I think banning ender pumps in the nether is "fixing" a problem that doesn't exist.
