### ISSUE TITLE
Crash back to launcher - zC 0.0.17

### ISSUE THREAD

**Issue by FuzzyJem** [warezit/zitCraft#28]
Items that I put in my inventory seem to crash my game. Not it seems to be an item from tconstruct

https://gist.github.com/FuzzyJem/4d45ea0560480f56800e

**Comment by FuzzyJem** [comment]
Same happened with paint brushes*

**Comment by warezit** [comment]
Care to elaborate on this?

You are giving me very little information to go on here.

Like, what was the piece of armor you were trying to equip? And, anything else you can think of that you can tell me about this?

**Comment by warezit** [comment]
Also, I highly doubt your "paint brush" issue is the EXACT same bug as what's happening here, but since you never reported anything, I have nothing to go on.

**Comment by FuzzyJem** [comment]
I believe it is the chest piece. I pulled it out of the transmutation tablet and put it in my inventory. seconds later the  game crashed back to launcher. The reason I said it was like the brush, (the mod name escapes me) was because the same exact thing happened. Pulled it out the transmutation tablet, threw it in my inventory, game crashed to launcher, Both of which resulted in me trying to connect to the server and getting kicked back to launcher.

**Comment by Benjaminjex** [comment]
Log: https://gist.github.com/Benjaminjex/9251ecee925da89d304d

I put a TiC armor piece (Traveller's stuff, but only the ones that go in the regular inventory equipper) into a table to modify it (forge, tinker's table) it crashes me to the launcher. Not sure if it goes here but it may be related.

**Comment by Rader2146** [comment]
@Benjaminjex can you re-log or does it crash again on join?

If you cannot re-log,  see if someone can destroy the table that you put the armor in (tell them not to open the GUI or they may crash too).

**Comment by Benjaminjex** [comment]
I can relog (I did it several times) the problem happens whenever I grab the item with my mouse and move it and set it in the table GUI that I crash

**Comment by warezit** [comment]
ProjectE is the cause of this problem, and has been removed in zC 2.0
