### ISSUE TITLE
Thaumic Energistics Bugs - zC 0.0.17

### ISSUE THREAD

**Issue by NubsMcGee** [warezit/zitCraft#29]
Lot's of bugs with Thaumic Energistics, the Essentia Drives don't seem to work, however, putting drums on storage buses does. The Essentia Terminal Dupes Essentia like there is no tomorrow. If it has at least 1 of your selected type, it will FILL your container to the brim.

**Comment by warezit** [comment]
Thaumcraft, Thaumic Energistics and AE2 have all been updated in zC 2.0. Let's revisit this issue in the new pack, and see if we can re-produce it.
