### ISSUE TITLE
Galactic Craft Oxygen Collector Bitchy-ness - zC 0.0.10

### ISSUE THREAD

**Issue by mprobison** [warezit/zitCraft#3]
Seeds from forestry/pam's shit will not produce oxygen via the Oxygen Collector. Most likely an issue with galactic suc--- Craft. A quick glance to see if a config file exists would be great for the next update.

**Comment by warezit** [comment]
Not producing "seeds" from crops might have something to do with HungerOverhaul, Spice Of Life, or Harvestcraft. Configs need to be looked into for this.

**Comment by warezit** [comment]
I have looked through the config for GalacticCraft, and I believe plants from Forestry and Pam's Harvest Craft are just simply not supported/cross-compatible with GalacticCraft for producing oxygen. As far as I am aware this is just an unsupported feature. 

I think if you want to produce oxygen in space (or in any GC dimension) you must use vanilla plants/trees/etc...
