### ISSUE TITLE
Twilight Forest Achievement Bug - zC 0.0.17

### ISSUE THREAD

**Issue by NubsMcGee** [warezit/zitCraft#30]
I'm unable to get the "Lich Hunter" achievement to complete preventing me from advancing through the twilight forest. I have seen someone else get the achievement, so it's working for some.

I have killed the lich 4 times, and confirmed over and over that all requirements are being met.

**Comment by warezit** [comment]
Try logging back into the server (when I am around), and I'll try advancing your progression thru the Twilight Forest mod via commands.
