### ISSUE TITLE
Crash on server login after logging out in an unloaded/corrupted chunk in The End. - zC 0.0.21

### ISSUE THREAD

**Issue by zunzibarr** [warezit/zitCraft#31]
I'm pretty sure it was an unloaded or corrupt chunk - nothing was in it, had that slow sluggish 'slide' you experience while going through it. Logged out to see if that would fix the chunk loading, and now crash upon server login.

**Comment by warezit** [comment]
Can you upload your client crash log to pastebin or Gist?

**Comment by zunzibarr** [comment]
.... Sorry for the rookie mistake. Here ya go! http://pastebin.com/gAK0nZwp

**Comment by warezit** [comment]
No worries, thanks for sharing the log!

The log looks like a generic chunk issue to me, not related to any mods.

I just tried logging into the server, and going to the End dimension, and I cannot go there, for some reason. I tried going thru an Enhanced Portal to the End, using an Ender Porter, and the Transportation thing from Draconic Evolution. None of which worked.

It seems to me like the End dimension may just be corrupted entirely.

I am investigating this more now.

**Comment by warezit** [comment]
@zunzibarr I fixed your player file to put you back at your base in the overworld, until I can get the End dimension reset/fixed.

Still working on it right now.

**Comment by warezit** [comment]
So, I didn't change anything with the server/world file, and I just tried going to the End.

It seems to be working fine now. I can take my Enhanced Portal to the End, just fine.

Please try going to the End again, and let me know if you have any issues...

**Comment by warezit** [comment]
I "think" this is fixed after I cleaned up the server/world file a bit; let me know here if you run into this again.
