### ISSUE TITLE
IC2 Naming Convention - zC 0.0.10

### ISSUE THREAD

**Issue by mprobison** [warezit/zitCraft#4]
All the shit in NEI pertaining to the IC2 has a bullshit naming convention. Everything is prefixed with the mod name, type, and finally the block name. Not really a game breaking issue, but is not neat.

**Comment by warezit** [comment]
I noticed this as well.

Not sure how to fix this. I have not looked into fixing this yet either. Any advice pertaining to this is  appreciated.

**Comment by warezit** [comment]
I searched Google for this a bit today, and I can't find anything pertaining to this. Any advice from anyone on this is appreciated.
