### ISSUE TITLE
Sleeping in bed crashes client. - zC 0.0.10

### ISSUE THREAD

**Issue by Rader2146** [warezit/zitCraft#5]
Pretty simple, yet have no idea why...

Right click on a bed to sleep and client crashes immediately. Confirmed a second time.

Crash Report
https://gist.github.com/Rader2146/4649332311912be56fb4

Will report issue to HungerOverhaul also.

**Comment by Rader2146** [comment]
https://gist.github.com/Rader2146/e8310c933c5b9ddc2dbe

Now seems to be multiple right click events.  This was from right clicking a wooden door to open in.

**Comment by warezit** [comment]
Looks like an issue with HungerOverhaul. Looking into this right now.

**Comment by warezit** [comment]
Posted on the Hunger Overhaul GitHub Issue Tracker here: https://github.com/progwml6/HungerOverhaul/issues/77

**Comment by Rader2146** [comment]
I'm sure that this is a HO thing.  I was reading on the HO github and the right click to harvest mechanic is (in the Dev's own words) "a bit of a hacky workaround".

Might need to disable right-click harvest in the configs.  Confirmed crash in singleplayer also.  Going to mess with client configs.

**Comment by warezit** [comment]
I see what you mean here: https://github.com/progwml6/HungerOverhaul/issues/35#issuecomment-59090026

Disabling the "right-click" feature in the HO configs might be the best option, until there is a better solution.

**Comment by warezit** [comment]
Removing HO in zC 0.0.12. Closed.
