### ISSUE TITLE
Essence berries wont grow - zC 0.0.10

### ISSUE THREAD

**Issue by FuzzyJem** [warezit/zitCraft#7]
Having an issue with essence berries growing, however, it doesnt seem to be affecting anyone else. Ive placed them down 3 days ago and they will not grow. some MIGHT grow to the second stage but will not complete the growing process. The only way to get them to grow past this is to use the Sigil of the green. Then, and only then,  they grow to the final stage and produce essence berries. Ive taken elevation into consideration... so i planted some down lower. still the same. Ive also gone back to my previous base before the server switched and placed them exactly where they were before to rule out a biome thing. still nothing. Ive also taken light into consideration, placing them in caves and in fully lit areas, with and without water.Seems odd that they wouldnt grow right next to another one that has naturally spawned in a cave.

As of right now i need to idle with a sigil above my bushes to get berries, which has killed me a few times since it takes life from ya.

**Comment by Rader2146** [comment]
I can't get them to grow either.

**Comment by FuzzyJem** [comment]
might actually be other berry bushes as well. ill check in a few when i get a stable connection

**Comment by warezit** [comment]
My berry bushes grow... but VERY slowly... I am using a Lily Pad of Fertility next to them tho... There are also these methods to help them grow faster... http://forum.feed-the-beast.com/threads/essence-berry.42448/

I am looking through the configs to see if there is another mod that is nerfing the growth rate of berry bushes.
