### ISSUE TITLE
(BC Silicon) Assembly Table error - zC 0.0.10

### ISSUE THREAD

**Issue by bulseyerocks** [warezit/zitCraft#8]
In order to make a 'Redstone Crystal', you must make an Assembly Table, ( lasers,) and a block of Redstone. The Assembly Table works perfectly fine from what I've experienced - besides the fact that Redstone Crystals are unable to be made. I put my block in and it takes nearly 20 minutes or more with 3 lasers and then nothing comes out, nothing goes into my inventory, nothing is to be seen. The assembly table works with other items, I believe all the other items, but not the Crystal.

**Comment by warezit** [comment]
I just tested this issue in creative single player on zitCraft 0.0.10.

I was able to craft a Redstone Crystal just fine. I used 30 lasers, and it took nearly 10 mins.

Are you sure the Redstone Crystal was not made? Did it drop thru the floor, or something? Or, stuck in a transfer node?

![2015-02-07_18 08 19](https://cloud.githubusercontent.com/assets/8278779/6094543/d42c7f06-aef3-11e4-862d-6e7920803b9c.png)
