### ISSUE TITLE
Large map overlay artifact. 

### ISSUE THREAD

**Issue by mprobison** [warezit/zitCraft#9]
Ender energy conduit (green tier 3) will cut through the expanded mini map while on the item bar. Cool fact, not really a game breaking thing. Just thought I'd share with the club. http://puu.sh/fCKKV/eb20b6cdb3.jpg

**Comment by warezit** [comment]
Small issue, but still relevant.

I think just a graphical "bug".

Not sure even how to address this/fix it. But, since this is "non-game-breaking" I am going to dis-regard it in the meantime, until it would become a actual problem.

Thanks for the heads up!
